// packages/ng-ui/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { interpret, interpreterCore } from '@ts-interpreter/interpreter-core';

@Component({
  standalone: true,
  selector: 'ts-interpreter-root',
  imports: [CommonModule],
  template: `
    <textarea (input)="handleInput($event)" cols="30" rows="10"></textarea>
    @if(inputText) {
      <button  (click)="handleSubmit()">Submit</button>
    }
    <pre>{{ outputTokens }} <pre>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  interpreterCore = interpreterCore();

  inputText = '';
  outputTokens = '';

  handleInput(e: Event) {
    this.inputText = (e.target as HTMLTextAreaElement).value;
  }

  handleSubmit() {
    this.outputTokens = JSON.stringify(interpret(this.inputText), null, 2);
  }
}

<ts-interpreter-nx-welcome
  [interpreterCore]="interpreterCore"
></ts-interpreter-nx-welcome>

// packages/react-ui/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { interpret } from '@ts-interpreter/interpreter-core';
import { useState } from 'react';

export function App() {
  const [code, setCode] = useState('');

  const [res, setRes] = useState('');

  function handleSubmit() {
    setRes(JSON.stringify(interpret(code), null, 2));
  }

  return (
    <>
      <textarea
        value={code}
        onChange={(e) => setCode(e.target.value)}
        cols={30}
        rows={10}
      ></textarea>
      {code ? <button onClick={handleSubmit}>Submit</button> : null}

      <pre>{res}</pre>
    </>
  );
}

export default App;
